package team2.domain.enums;

public enum EntityType {
    EVENT_DUTY,
    PERSON,
    ACCOUNT,
    INSTRUMENTATION,
    MUSICALWORK,
    REQUEST,
    DUTY_DISPOSITION,
    INSTRUMENT,
    INSTRUMENT_TYPE,
    SPECIAL_INSTRUMENTATION_TYPE
}
